#pragma once
#include <Windows.h>
#include <iostream>
#include <tchar.h>
using namespace std;
enum
{
	CLIENT_LOGIN,				// 上线包
	CLIENT_GET_OUT_REQUIRE,
	CLIENT_GET_OUT_REPLY,
	CLIENT_REMOTE_MESSAGE_REQUIRE,
	CLIENT_REMOTE_MESSAGE_REPLY,
	CLIENT_REMOTE_MESSAGE_COMPLETE,
	CLIENT_SHUT_DOWN_REQUIRE,
	CLIENT_SHUT_DOWN_REPLY,
	CLIENT_CMD_MANAGER_REQUIRE,
	CLIENT_CMD_MANAGER_REPLY,
	CLIENT_PROCESS_MANAGER_REQUIRE,
	CLIENT_PROCESS_MANAGER_REPLY,
	CLIENT_PROCESS_MANAGER_REFRESH_REQUIRE,
	CLIENT_PROCESS_MANAGER_KILL_REQUIRE,
	CLIENT_OPEN_PROCESS_REQUIRE,
	CLIENT_WINDOW_MANAGER_REQUIRE,
	CLIENT_WINDOW_MANAGER_REPLY,
	CLIENT_WINDOW_MANAGER_REFRESH_REQUIRE,
	CLIENT_REMOTE_CONTROLLER_REQUIRE,
	CLIENT_REMOTE_CONTROLLER_REPLY,
	CLIENT_REMOTE_CONTROLLER_FIRST_SCREEN,
	CLIENT_REMOTE_CONTROLLER_NEXT_SCREEN,
	CLIENT_REMOTE_CONTROLLER_CONTROL_REQUIRE,
	CLIENT_REMOTE_CONTROLLER_BLOCK_INPUT_REQUIRE,
	CLIENT_REMOTE_CONTROLLER_GET_CLIPBOARD_REQUIRE,
	CLIENT_REMOTE_CONTROLLER_SET_CLIPBOARD_REQUIRE,
	CLIENT_REMOTE_CONTROLLER_GET_CLIPBOARD_REPLY,
	CLIENT_REMOTE_CONTROLLER_SET_CLIPBOARD_REPLY,
	CLIENT_FILE_MANAGER_REQUIRE,
	CLIENT_FILE_MANAGER_REPLY,
	CLIENT_FILE_MANAGER_FILE_LIST_REQUIRE,
	CLIENT_FILE_MANAGER_FILE_LIST_REPLY,
	CLIENT_FILE_MANAGER_SEND_FILE_INFORMATION,
	CLIENT_FILE_MANAGER_TRANSFER_MODE_REQUIRE,        //在客户端中发现了有重名文件
	CLIENT_FILE_MANAGER_SET_TRANSFER_MODE,
	CLIENT_FILE_MANAGER_FILE_DATA,
	CLIENT_FILE_MANAGER_FILE_DATA_CONTINUE,
	CLIENT_AUDIO_MANAGER_REQUIRE,
	CLIENT_AUDIO_MANAGER_REPLY,
	CLIENT_AUDIO_MANAGER_RECORD_DATA,
	CLIENT_VIDEO_MANAGER_REQUIRE,
	CLIENT_SERVICE_MANAGER_REQUIRE,
	CLIENT_SERVICE_MANAGER_REPLY,
	CLIENT_SERVICE_MANAGER_CONFIG_REQUIRE,
	CLIENT_REGISTER_MANAGER_REQUIRE,
	CLIENT_REGISTER_MANAGER_REPLY,
	CLIENT_REGISTER_MANAGER_DATA_CONTINUE,
	CLIENT_REGISTER_MANAGER_PATH_DATA_REPLY,
	CLIENT_REGISTER_MANAGER_KEY_DATA_REPLY,
	CLIENT_GO_ON,
	CLIENT_PROCESS_QUERY_REQUIRE,
	CLIENT_REMOTE_CHANGE_MEMORY_REQUIRE,
	CLIENT_FIRST_SCAN_REQUIRE,
	CLIENT_FIRST_SCAN_REPLY,
	CLIENT_SCAN_AGAIN_REPLY,
	CLIENT_SCAN_AGAIN_REQUIRE,
	CLIENT_EDIT_VALUE_REQUIRE,
	CLIENT_VIRTUAL_MEMORY_MAPPING_REQUIRE,
	CLIENT_VIRTUAL_MEMORY_MAPPING_REPLY,
	CLIENT_UPDATE_VMMAP_SYSTEM_INFO_REQUIRE,
	CLIENT_UPDATE_VMMAP_SYSTEM_INFO_REPLY,
	
	

};

enum
{
	CMD_MANAGER_DIALOG = 1,
	PROCESS_MANAGER_DIALOG,
	WINDOW_MANAGER_DIALOG,
	REMOTE_CONTROLL_DIALOG,
	FILE_MANAGER_DIALOG,
	SERVICE_MANAGER_DIALOG,
	REGISTER_MANAGER_DIALOG,
};
#define UM_CLIENT_LOGIN                  WM_USER+1000
#define UM_OPEN_REMOTE_MESSAGE_DIALOG    WM_USER+1005
#define UM_OPEN_PROCESS_MANAGER_DIALOG  WM_USER+1007
#define UM_OPEN_CHANGE_MEMORY_DIALOG    WM_USER+1009
#define UM_OPEN_EDIT_VALUE_DIALOG       WM_USER+1010
#define UM_OPEN_VMMAP_DIALOG             WM_USER+1011